### ISSUE TITLE
PHP Fatal error:  Uncaught Error: Call to undefined function split()

### ISSUE THREAD

**Issue by mmomasters** [ircf/sendy_smtp_bounce#11]
When : php /home/mailing/public_html/bounce.php

PHP Fatal error:  Uncaught Error: Call to undefined function split() in /home/mailing/public_html/includes/helpers/bounce_driver.class.php:229
Stack trace:
#0 /home/mailing/public_html/bounce.php(28): BounceHandler->get_the_facts('Return-Path: <>...')
#1 {main}
  thrown in /home/mailing/public_html/includes/helpers/bounce_driver.class.php on line 229

https://www.php.net/manual/en/function.split.php
Warning
This function was DEPRECATED in PHP 5.3.0, and REMOVED in PHP 7.0.0.

**Comment by mmomasters** [comment]
Fixed by replacing by explode

Pull request ready

**Comment by mbautista** [comment]
Hello,
Thank you for this fix ! :) I just merged it : https://github.com/ircf/sendy_smtp_bounce/pull/12
Indeed this bounce driver is not maintained anymore and still has many bugs.
Mathieu.
