### ISSUE TITLE
Doesnt Detect Bounces

### ISSUE THREAD

**Issue by dragonglobal** [ircf/sendy_smtp_bounce#5]
When getting bounces into the inbox I can see the script connect and read the messages.

But sadly it's not recording the bounces.

I've had little look and bounce.php is getting the first part;

`array(1) {
  [0]=>
  array(4) {
    ["action"]=>
    string(12) "autoresponse"
    ["status"]=>
    string(0) ""
    ["recipient"]=>
    string(58) "thisshouldnotwork@noideawherethiswillendupasitsnotreal.com"
    ["autoresponse"]=>
    string(28) "Auto-submitted: auto-replied"
  }
}`

but then its not seeing that as a bounce, therefore not progressing to the next step, which is;

`if (
    !empty($multiArray[0]['action']) &&
    !empty($multiArray[0]['status']) &&
    !empty($multiArray[0]['recipient']) &&
    $multiArray[0]['action']=='failed'
  ) {`

All the bounces im getting seem to be showing that ( the subject is the same for all ), however the body differs... 

**Bounce 1**
SMTP error from remote mail server after RCPT TO:<bouncetest@tribulant.com>:
    550 No such person at this address.

**Bounce 2**
 thisshouldnotwork@noideawherethiswillendupasitsnotreal.com
    Unrouteable address

any ideas?

**Comment by dragonglobal** [comment]
Just wanted to give a follow up to this;

Looking in our bounce inbox, zero of the bounces are getting recorded into sendy but they are being read.

bounce.php is saying all of them are 

Auto-submitted: auto-replied

**Comment by dragonglobal** [comment]
Managed to fix it.

There is a php error in bounce_driver_class.php line 638

`$ret = "";`

It should be 

`$ret = [];`

As im on php 7.4, seems to prefer it like that

Thanks

**Comment by mbautista** [comment]
Thanks for the fix.
I didn't tested this script with php7.3+
Mathieu.
